# Generated by Django 5.2.6 on 2026-09-01 06:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('budget_year', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('manifest_path', models.CharField(max_length=500)),
                ('formula_manifest_hash', models.CharField(max_length=64)),
                ('rule_version', models.CharField(default='R1', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', '管理端'), ('PROJECT', '项目端')], default='PROJECT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('budget_year', models.PositiveIntegerField()),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('SETUP', '设置中'), ('OPEN', '开放上传'), ('ADJUSTING', '管理调整'), ('READY_TO_FREEZE', '待冻结'), ('FROZEN', '已冻结')], default='SETUP', max_length=24)),
                ('p1_threshold_cents', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget_year', 'revision_no'), name='uniq_cycle_revision')],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=40)),
                ('baseline_total_cents', models.BigIntegerField(default=0)),
                ('delta_cents', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ISSUED', '已下发'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
            ],
        ),
        migrations.CreateModel(
            name='FreezeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STAGING', '生成中'), ('COMPLETE', '完成'), ('FAILED', '失败')], default='STAGING', max_length=20)),
                ('directory', models.CharField(blank=True, max_length=500)),
                ('manifest_path', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('relative_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='budgeting.freezesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='UploadVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECEIVED', '已接收'), ('PROCESSING', '处理中'), ('REJECTED', '已拒绝'), ('VALIDATED', '已校验'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('SUPERSEDED', '已替换')], default='RECEIVED', max_length=24)),
                ('original_name', models.CharField(default='', max_length=255)),
                ('original_path', models.CharField(max_length=500)),
                ('recalculated_path', models.CharField(blank=True, max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.templateversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
                ('current_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', '排队中'), ('RUNNING', '运行中'), ('DONE', '完成'), ('FAILED', '失败')], default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('row_label', models.CharField(blank=True, max_length=240)),
                ('period', models.CharField(max_length=40)),
                ('unit', models.CharField(choices=[('MONEY', '金额'), ('COUNT', '数量'), ('RATIO', '比率')], max_length=20)),
                ('value_int', models.BigIntegerField(default=0)),
                ('ratio_num', models.BigIntegerField(blank=True, null=True)),
                ('ratio_den', models.BigIntegerField(blank=True, null=True)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_cell', models.CharField(max_length=20)),
                ('source_formula', models.TextField(blank=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting.budgetcycle')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting.project')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=40)),
                ('baseline_cents', models.BigIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('allocated_delta_cents', models.BigIntegerField(default=0)),
                ('target_cents', models.BigIntegerField(default=0)),
                ('latest_value_cents', models.BigIntegerField(blank=True, null=True)),
                ('difference_cents', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', '待项目重传'), ('CONFIRMED', '已确认'), ('CANCELLED', '已取消')], default='OPEN', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.adjustmentbatch')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
                ('latest_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(max_length=40)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('P0', '阻断'), ('P1', '确认'), ('P2', '提示')], max_length=2)),
                ('code', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('actual_value', models.CharField(blank=True, max_length=120)),
                ('expected_value', models.CharField(blank=True, max_length=120)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledgement_note', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='budgeting.validationrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadversion',
            index=models.Index(fields=['project', 'cycle', 'status'], name='budgeting_u_project_5cf307_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcycle',
            constraint=models.UniqueConstraint(fields=('project', 'cycle'), name='uniq_project_cycle'),
        ),
        migrations.AddConstraint(
            model_name='normalizedvalue',
            constraint=models.UniqueConstraint(fields=('upload', 'report_code', 'row_code', 'period'), name='uniq_norm_value'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentline',
            constraint=models.UniqueConstraint(fields=('batch', 'project'), name='uniq_adjustment_project'),
        ),
        migrations.AddConstraint(
            model_name='adjustmentline',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cycle', 'project', 'report_code', 'row_code', 'period'), name='uniq_open_adjustment_target'),
        ),
    ]
