# Generated by Django 5.2.6 on 2026-09-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_budgetcycle_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentbatch',
            name='cascade',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='driver',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='driver_label',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='from_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.project'),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='target_room_rev_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adjustmentbatch',
            name='to_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
        ),
    ]
