# Generated by Django 5.2.6 on 2026-09-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_adjustmentbatch_cascade_adjustmentbatch_driver_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adjustmentline',
            name='uniq_adjustment_project',
        ),
    ]
