# Generated by Django 5.2.6 on 2026-09-07 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_remove_adjustmentline_uniq_adjustment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedvalue',
            name='data_kind',
            field=models.CharField(blank=True, choices=[('ACTUAL', '实际'), ('FORECAST', '预测'), ('BUDGET', '预算')], max_length=12),
        ),
        migrations.AddField(
            model_name='normalizedvalue',
            name='data_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedvalue',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('inputs', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('rule_version', models.CharField(default='FIXED_COST_V2', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('READY', '已测算'), ('ISSUED', '已下发'), ('FAILED', '失败')], default='DRAFT', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.uploadversion')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.adjustmentbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', '待回复'), ('ANSWERED', '已回复'), ('CLOSED', '已关闭')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='budgeting.managementquestion')),
            ],
        ),
    ]
