# Generated by Django 5.2.6 on 2026-09-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_backfill_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcycle',
            name='source_budget_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
