# Generated by Django 5.2.6 on 2026-09-10 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_budget_cycle_rehearsal_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_project', to='budgeting.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialIndicatorBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('data_type', models.CharField(choices=[('ACTUAL', '实际'), ('FORECAST', '预测'), ('BUDGET', '预算')], max_length=12)),
                ('unit', models.CharField(max_length=12)),
                ('original', models.FileField(upload_to='special_indicators/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=20)),
                ('month', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=24, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='budgeting.specialindicatorbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.indicatorproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'project', 'indicator', 'month'), name='unique_special_indicator_month')],
            },
        ),
    ]
