# Generated by Django 5.2.6 on 2026-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0008_indicatorproject_specialindicatorbatch_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specialindicatorbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('cycle__isnull', True)), fields=('year', 'data_type'), name='unique_active_special_actual'),
        ),
        migrations.AddConstraint(
            model_name='specialindicatorbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('cycle__isnull', False)), fields=('year', 'data_type', 'cycle'), name='unique_active_special_budget'),
        ),
    ]
