# Generated by Django 5.2.6 on 2026-09-14 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0009_specialindicatorbatch_unique_active_special_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_year', models.PositiveIntegerField()),
                ('data_kind', models.CharField(choices=[('ACTUAL', '实际'), ('FORECAST', '预测')], max_length=12)),
                ('report_code', models.CharField(choices=[('PL_TOTAL_WINE', '酒店损益总表（含名酒）'), ('PL_TOTAL_NOWINE', '酒店损益总表（不含名酒）'), ('PL_ZZ_WINE', '损益表（含名酒）（拆中智）'), ('PL_ZZ_NOWINE', '损益表（不含名酒）（拆中智）')], max_length=40)),
                ('money_unit', models.CharField(default='yuan', max_length=8)),
                ('original_name', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('proposal', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='normalizedvalue',
            name='history_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.historicalimport'),
        ),
        migrations.CreateModel(
            name='HistoricalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_code', models.CharField(max_length=120)),
                ('row_label', models.CharField(max_length=240)),
                ('period', models.CharField(max_length=40)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('value_int', models.BigIntegerField(default=0)),
                ('ratio_num', models.BigIntegerField(blank=True, null=True)),
                ('ratio_den', models.BigIntegerField(blank=True, null=True)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_cell', models.CharField(max_length=20)),
                ('source_formula', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='budgeting.historicalimport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='historicalimport',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('project', 'data_year', 'data_kind', 'report_code'), name='unique_active_historical_source'),
        ),
        migrations.AddConstraint(
            model_name='historicalvalue',
            constraint=models.UniqueConstraint(fields=('import_batch', 'row_code', 'period'), name='unique_historical_cell'),
        ),
    ]
