# Generated by Django 5.2.6 on 2026-09-16 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0012_processing_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.PositiveIntegerField(unique=True)),
                ('revision_token', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='freezesnapshot',
            name='history_bindings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='uploadversion',
            name='history_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetcycle',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetplan'),
        ),
        migrations.CreateModel(
            name='HistoryBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('source_identity', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('differences', models.JSONField(default=list)),
                ('status', models.CharField(default='LOCKED', max_length=12)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.historybaseline')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBaselineValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('data_year', models.PositiveIntegerField()),
                ('data_kind', models.CharField(max_length=12)),
                ('period', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=20)),
                ('value_int', models.BigIntegerField()),
                ('ratio_num', models.BigIntegerField(blank=True, null=True)),
                ('ratio_den', models.BigIntegerField(blank=True, null=True)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_cell', models.CharField(blank=True, max_length=20)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='budgeting.historybaseline')),
            ],
        ),
        migrations.CreateModel(
            name='PlanHistoryBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('binding_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.historybaseline')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
            ],
        ),
        migrations.AddField(
            model_name='uploadversion',
            name='history_binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.planhistorybinding'),
        ),
        migrations.CreateModel(
            name='PlanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='historybaseline',
            constraint=models.UniqueConstraint(fields=('project', 'revision'), name='uniq_history_revision'),
        ),
        migrations.AddConstraint(
            model_name='historybaselinevalue',
            constraint=models.UniqueConstraint(fields=('baseline', 'report_code', 'row_code', 'data_year', 'data_kind', 'period'), name='uniq_baseline_value'),
        ),
        migrations.AddConstraint(
            model_name='planhistorybinding',
            constraint=models.UniqueConstraint(fields=('plan', 'project', 'revision'), name='uniq_plan_history_revision'),
        ),
        migrations.AddConstraint(
            model_name='planproject',
            constraint=models.UniqueConstraint(fields=('plan', 'project'), name='uniq_plan_project'),
        ),
    ]
