# Generated by Django 5.2.6 on 2026-09-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0013_annual_plan_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=40)),
                ('row_code', models.CharField(max_length=120)),
                ('period', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=20)),
                ('comparator', models.CharField(max_length=2)),
                ('target_int', models.BigIntegerField()),
                ('metric_kind', models.CharField(max_length=20)),
                ('sign_multiplier', models.SmallIntegerField(default=1)),
                ('evidence', models.TextField()),
                ('rule_version', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TargetEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.uploadversion')),
            ],
        ),
        migrations.CreateModel(
            name='TargetEvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24)),
                ('actual_int', models.BigIntegerField(null=True)),
                ('favorable_delta', models.BigIntegerField(null=True)),
                ('shortfall', models.BigIntegerField(null=True)),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.targetconstraint')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='budgeting.targetevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='TargetSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('issued_sequence', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('source', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('origin_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetcycle')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.budgetplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.project')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.targetset')),
            ],
        ),
        migrations.AddField(
            model_name='targetevaluation',
            name='target_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgeting.targetset'),
        ),
        migrations.AddField(
            model_name='targetconstraint',
            name='target_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constraints', to='budgeting.targetset'),
        ),
        migrations.AddConstraint(
            model_name='targetset',
            constraint=models.UniqueConstraint(fields=('plan', 'project', 'revision'), name='uniq_plan_project_target_revision'),
        ),
        migrations.AddConstraint(
            model_name='targetconstraint',
            constraint=models.UniqueConstraint(fields=('target_set', 'report_code', 'row_code', 'period', 'comparator'), name='uniq_target_scope_comparator'),
        ),
    ]
