# Generated by Django 5.2.6 on 2026-09-23 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0014_annual_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMetricBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to='management_metrics/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('money_unit', models.CharField(max_length=8)),
                ('data_kind', models.CharField(max_length=12)),
                ('report_code', models.CharField(max_length=40)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=10, max_digits=28, null=True)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_cell', models.CharField(max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='budgeting.managementmetricbatch')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.indicatorproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'project', 'metric', 'year', 'month'), name='unique_management_metric_value'), models.CheckConstraint(condition=models.Q(('month__gte', 0), ('month__lte', 12)), name='management_metric_month_range')],
            },
        ),
    ]
