"""Generate reproducible wheel hashes from official PyPI metadata, without installing."""
import argparse
import json
from pathlib import Path
import subprocess

PINS = {
    'Django': ('5.2.6', ''), 'asgiref': ('3.12.1', ''), 'sqlparse': ('0.6.0', ''),
    'tzdata': ('2025.2', 'sys_platform == "win32"'),
    'openpyxl': ('3.1.5', ''), 'et_xmlfile': ('2.0.0', ''),
    'gunicorn': ('23.0.0', 'sys_platform != "win32"'),
    'packaging': ('26.0', 'sys_platform != "win32"'),
    'whitenoise': ('6.9.0', ''), 'waitress': ('3.0.2', ''), 'psutil': ('7.0.0', ''),
}


def generate(output):
    lines = ['# Official PyPI wheel SHA256 values; generated by scripts/build_dependency_lock.py.',
             '# Includes all published wheel platforms for these exact versions.',
             '# Windows execution remains a native CI acceptance requirement.', '--index-url https://pypi.org/simple', '']
    provenance = {}
    for name, (version, marker) in PINS.items():
        url = f'https://pypi.org/pypi/{name}/{version}/json'
        metadata = json.loads(subprocess.check_output(['curl', '--fail', '--silent', '--show-error', '--max-time', '30', url], timeout=35))
        wheels = [item for item in metadata['urls'] if item['packagetype'] == 'bdist_wheel' and not item.get('yanked')]
        if not wheels:
            raise ValueError(f'No official wheels: {name} {version}')
        hashes = sorted({item['digests']['sha256'] for item in wheels})
        line = name + '==' + version + ('; ' + marker if marker else '')
        lines.append(line + ' \\')
        lines.extend('    --hash=sha256:' + value + (' \\' if index < len(hashes) - 1 else '') for index, value in enumerate(hashes))
        lines.append('')
        provenance[name] = {'version': version, 'metadata_url': url, 'wheels': {item['filename']: item['digests']['sha256'] for item in wheels}}
    Path(output).write_text('\n'.join(lines), encoding='utf-8')
    Path(output).with_suffix('.provenance.json').write_text(json.dumps(provenance, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path('requirements-update.lock'))
    generate(parser.parse_args().output)
